---
title: 'Text Mining with R'
subtitle: '(part 1)'
output: html_document
---

***

## Chapter 1: The Tidy Text Format

***

**token**: *meaningful unit of text for analysis*

**tokenization**: *breaking text into tokens*

```{r, message = F, echo = F}
# Loading in packages...

library(tidytext)
library(scales)
library(tidyverse)

# Loading in data...


```

```{r, echo = T, eval = F}
# Emily Dickinson example, pg. 2-4

text <- c("Because I could not stop for Death -",
          "He kindly stopped for me -",
          "The Carriage held but just Ourselves -",
          "and Immortality")

text_df <- tibble(line = 1:4, text = text)
text_df

text_df %>% 
  unnest_tokens(word, text)

text_df %>% 
  unnest_tokens(word, text, to_lower = FALSE)

```

```{r, echo = T, eval = F}
# 'janeaustenr' intro, pg. 4-7

library(janeaustenr)

original_books <- austen_books() %>% 
  group_by(book) %>% 
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]",
                                                 ignore_case = TRUE)))) %>% 
  ungroup()
original_books

tidy_books <- original_books %>% 
  unnest_tokens(word, text)
tidy_books

data(stop_words)
tidy_books <- tidy_books %>% 
  anti_join(stop_words, by = "word")

tidy_books %>% 
  count(word, sort = TRUE)

tidy_books %>% 
  count(word, sort = TRUE) %>% 
  filter(n > 600) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n)) + geom_col() + xlab(NULL) + coord_flip()

```

**stop words**: *read more [here](https://en.wikipedia.org/wiki/Stop_words)*

```{r, echo = T, eval = F, message = F, warning = F}
# 'gutenbergr' intro, pg. 7-

library(gutenbergr)

## H.G. Wells

hgwells <- gutenberg_download(c(35, 36, 5230, 159))

tidy_hgwells <- hgwells %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words, by = "word")

tidy_hgwells %>% 
  count(word, sort = TRUE)

## Brontë Sisters

bronte <- gutenberg_download(c(1260, 768, 969, 9182, 767))

tidy_bronte <- bronte %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words, by = "word")

tidy_bronte %>% 
  count(word, sort = TRUE)

## binding both with Austen...

frequency <- bind_rows(mutate(tidy_bronte, author = "Brontë Sisters"),
                       mutate(tidy_hgwells, author = "H.G. Wells"),
                       mutate(tidy_books, author = "Jane Austen")) %>% 
  mutate(word = str_extract(word, "[a-z']+")) %>% 
  count(author, word) %>% 
  group_by(author) %>% 
  mutate(proportion = n / sum(n)) %>% 
  select(-n) %>% 
  spread(author, proportion) %>% 
  gather(author, proportion, `Brontë Sisters`:`H.G. Wells`)

ggplot(frequency, aes(x = proportion, y = `Jane Austen`,
                      color = abs(`Jane Austen` - proportion))) +
  geom_abline(color = "gray40", lty = 2) + 
  geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) + 
  geom_text(aes(label = word), check_overlap = TRUE, vjust = 1.5) + 
  scale_x_log10(labels = percent_format()) + 
  scale_y_log10(labels = percent_format()) +
  scale_color_gradient(limits = c(0, 0.001),
                       low = "darkslategray4", high = "gray75") +
  facet_wrap(~author, ncol = 2) +
  theme(legend.position = "none") +
  labs(y = "Jane Austen", x = NULL)
  
## Correlation test

cor.test(data = frequency[frequency$author == "Brontë Sisters",],
         ~ proportion + `Jane Austen`)

cor.test(data = frequency[frequency$author == "H.G. Wells",],
         ~ proportion + `Jane Austen`)

```

***Chapter 1 summary***: 

